#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 07 15:43:56 MST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=
enableShaders=true
